// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TYz-NOlWfc-BMcChAgp0KH-Y71ozneA',
    appId: '1:755498942514:android:afaa0db76329c52060fc2b',
    messagingSenderId: '755498942514',
    projectId: 'eloquent-hour-445710-s0',
    storageBucket: 'eloquent-hour-445710-s0.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzmYkGBH7yyAHGbiaI7eQtf9JUJxsGO4Y',
    appId: '1:755498942514:web:a0f161c2c866161560fc2b',
    messagingSenderId: '755498942514',
    projectId: 'eloquent-hour-445710-s0',
    authDomain: 'eloquent-hour-445710-s0.firebaseapp.com',
    storageBucket: 'eloquent-hour-445710-s0.firebasestorage.app',
    measurementId: 'G-LC26H98S36',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFHOINQCvvWwXOeYnXBMID4DlMeaRAuJM',
    appId: '1:755498942514:ios:6cf659b7eb1b55ea60fc2b',
    messagingSenderId: '755498942514',
    projectId: 'eloquent-hour-445710-s0',
    storageBucket: 'eloquent-hour-445710-s0.firebasestorage.app',
    iosClientId: '755498942514-7odheusu58t3ht2n3pl9o6k2o7vcm71v.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
